# Generated by Django 5.0.1 on 2024-02-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_old_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_cart',
        ),
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
